### ISSUE TITLE
testing all the mirros is time consuming, and a possible solution

### ISSUE THREAD

**Issue by xtbgtraining** [GuangchuangYu/mirrorselect#1]
Dear Dr. Yu,

Your package is cool, however it is very time consuming to wait for testing all the mirrors globally.
So I think it might be better to add another argument to tell R to only test mirrors from a specific country.

And I tried to modify part of  your codes, and tested it. And it worked well.
I wonder whether you can add this function and make an updated version of your package ?

Best!!
Jingxin

#######
get_mirror <- function(repo = "CRAN", country = "cn") {
    if  (repo == "CRAN") {
        return(get_mirror_cran(country))
    }

    get_mirror_bioc()
}

get_mirror_cran <- function(country = "cn") {
    library(magrittr)
    utils::getCRANmirrors()$URL %>% grep(pattern = paste(".", country, "/", sep = ""), value=TRUE)
}

get_mirror_bioc <- function(country = "cn") {
    library(magrittr)
    .getMirrors <- utils::getFromNamespace('.getMirrors', 'utils')
    .getMirrors("https://bioconductor.org/BioC_mirrors.csv",
                file.path(R.home("doc"), "BioC_mirrors.csv"),
                all = FALSE, local.only = FALSE)$URL%>% grep(pattern = paste(".", country, "/", sep = ""), value=TRUE)
}

**Comment by GuangchuangYu** [comment]
a pull request is welcome :)

**Comment by xtbgtraining** [comment]
> a pull request is welcome :)

sure, I did it.

**Comment by GuangchuangYu** [comment]
<https://github.com/GuangchuangYu/mirrorselect/pull/2>.
